### ISSUE TITLE
AMQ configuration issues

### ISSUE THREAD

**Issue by dineshkumar23cts** [easytaxibr/newrelic_activemq#5]
Team,

We have instrumented the New Relic AMQ plugin in the server but facing some code error, please help us on the issue.

PFB error for reference to the installation error.
 
[root@_hostname_ newrelic_activemq-master]# ./newrelic_activemq.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./newrelic_activemq.rb:4:in `<main>'

Kindly let me know what is the troubleshooting steps further.

Regards,
Dinesh Kumar R

**Comment by stupied4ever** [comment]
@dineshkumar23cts in which ruby version ?

**Comment by dineshkumar23cts** [comment]
> @dineshkumar23cts in which ruby version ?

@stupied4ever - Ruby version (ruby 2.0.0p648 (2015-12-16) [x86_64-linux])

**Comment by stupied4ever** [comment]
@dineshkumar23cts  can you run `gem list` plz? I think you dont have bundler installed.

**Comment by dineshkumar23cts** [comment]
> @dineshkumar23cts can you run `gem list` plz? I think you dont have bundler installed.

@stupied4ever Pls find below for gem list command output

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.7.8)
io-console (0.4.2)
json (1.7.7)
net-http-persistent (2.8)
psych (2.0.0)
rdoc (4.0.0)
rubygems-update (2.7.7)
thor (0.19.1)

Bundler is installed but while installing NR AMQ, getting error as missing gems.

**Comment by heidini** [comment]
For our AMQ, the Hawitio console  was disabled
Can we configure the plugin using the ssl connection?
